# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sledge-Cache-FastMmap
version:      0.01
version_from: lib/Sledge/Cache/FastMmap.pm
installdirs:  site
requires:
    Cache::FastMmap:               1.09
    Sledge::Cache:                 0.01
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
